### ISSUE TITLE
Example qcgpu_statevector.py fails Linux x86_64 NVidia GeForce GT 540M 

### ISSUE THREAD

**Issue by jwoehr** [qiskit-community/qiskit-qcgpu-provider#14]
### Problem
Example `qcgpu_qasm.py` succeeds on my Linux x86_64 system but `qcgpu_statevector.py` fails as follows:
```
(qiskit_dev_venv3) jax@varian:~/work/QISKit/DEV/qiskit-community-qcgpu-provider/examples$ python qcgpu_statevector.py
/home/jax/.local/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.5) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
QCGPU backends:  [<QCGPUStatevectorSimulator('statevector_simulator') from QCGPU Provider()>, <QCGPUQasmSimulator('qasm_simulator') from QCGPU Provider()>]
Choose platform:
[0] <pyopencl.Platform 'NVIDIA CUDA' at 0x1236c70>
Choice [0]:0
Set the environment variable PYOPENCL_CTX='0' to avoid being asked again.
simulation:  Result(backend_name='statevector_simulator', backend_version='1.0.0', job_id='d60d4bda-a087-4eb5-a1b4-e4b49265c7c1', qobj_id='2706361b-a8c8-4ebd-9b77-6b69c65a6319', results=[ExperimentResult(data=ExperimentResultData(statevector=[(0.7071067690849304+0j), 0j, 0j, (0.7071067690849304+0j)]), meas_level=2, shots=1, success=True, time_taken=0.009001016616821289)], success=True, time_taken=0.009790897369384766)
Traceback (most recent call last):
  File "/home/jax/work/QISKit/DEV/qiskit-terra/qiskit/result/result.py", line 266, in _get_experiment
    return next(result for result in self.results
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qcgpu_statevector.py", line 35, in <module>
    print(result_sim.get_statevector(qc))
  File "/home/jax/work/QISKit/DEV/qiskit-terra/qiskit/result/result.py", line 202, in get_statevector
    return postprocess.format_statevector(self.data(experiment)['statevector'],
  File "/home/jax/work/QISKit/DEV/qiskit-terra/qiskit/result/result.py", line 104, in data
    return self._get_experiment(experiment).data.to_dict()
  File "/home/jax/work/QISKit/DEV/qiskit-terra/qiskit/result/result.py", line 271, in _get_experiment
    key)
qiskit.exceptions.QiskitError: 'Data for experiment "circuit0" could not be found.'
```
### System info
```
(qiskit_dev_venv3) jax@varian:~/work/QISKit/DEV/qiskit-community-qcgpu-provider/examples$ nvidia-smi
Sun Sep 22 18:58:49 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.116                Driver Version: 390.116                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 540M     Off  | 00000000:01:00.0 N/A |                  N/A |
| N/A   52C    P0    N/A /  N/A |    375MiB /   963MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+
(qiskit_dev_venv3) jax@varian:~/work/QISKit/DEV/qiskit-community-qcgpu-provider/examples$ uname -a
Linux varian 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
(qiskit_dev_venv3) jax@varian:~/work/QISKit/DEV/qiskit-community-qcgpu-provider/examples$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by adamisntdead** [comment]
Will try reproduce tonight

**Comment by adamisntdead** [comment]
The issue was that I forgot to pass through the circuit's name, which meant that when looking for the output state vector, the schema didn't have the field. Should be fixed now.

**Comment by jwoehr** [comment]
Works for me, thanks.
